type: remap
inputs:
  - vector_agent
source: |
  if is_string(.host) {
    .host = { "name": .host }
  }

  parsed, err = parse_json(.message)
  if err == null {
      . = merge!(., parsed)
      del(.message)
  }
