type: route
inputs:
  - parse_json
  - parse_syslog
route:
  # Route source-specific logs
  hubble_flow_logs:
    type: vrl
    source: .@source == "hubble_flow"
  kubernetes_logs:
    type: vrl
    source: .@source == "kubernetes"
  kubernetes_audit_logs:
    type: vrl
    source: .@source == "kubernetes_audit"
  unifi_logs:
    type: vrl
    source: .@source == "unifi"
  # Route application-specific logs
  envoy_access_logs:
    type: vrl
    source: .@dataset == "kubernetes.envoy"
  vault_audit_logs:
    type: vrl
    source: '.@dataset == "kubernetes.vault" && (!is_null(.auth.accessor) || .@module == "expiration")'
