transforms:
  transform_hubble_flow_logs:
    type: remap
    inputs:
      - route_logs.hubble_flow_logs
    source: |
      if exists(.flow) {
        flow = del(.flow)
        . = merge!(., flow)

        .destination.id = del(.destination.ID)
        .destination.ip = del(.IP.destination)
        .destination.pod = del(.destination.pod_name)
        .destination.port = compact([.l4.TCP.destination_port, .l4.UDP.destination_port])[0]

        .event_type = .event_type.type
        .node = del(.node_name)
        .summary = del(.Summary)

        .source.id = del(.source.ID)
        .source.ip = del(.IP.source)
        .source.pod = del(.source.pod_name)
        .source.port = compact([.l4.TCP.source_port, .l4.UDP.source_port])[0]

        .type = del(.Type)

        del(.emitter)
        del(.ethernet)
        del(.host)
        del(.interface)
        del(.IP)
        del(.l4)
      }
