transforms:
  transform_kubernetes_audit_logs:
    type: remap
    inputs:
      - route_logs.kubernetes_audit_logs
    source: |
      .api_version = del(.apiVersion)
      .audit_id = del(.auditID)
      .impersonated_user = del(.impersonatedUser)
      .object_ref = del(.objectRef)
      .request_uri = del(.requestURI)
      .response_status = del(.responseStatus)
      .source_ips = del(.sourceIPs)
      .user_agent = del(.userAgent)

      del(.requestReceivedTimestamp)
      del(.stageTimestamp)
