transforms:
  transform_kubernetes_logs:
    type: remap
    inputs:
      - route_logs.kubernetes_logs
    source: |
      .kubernetes.container = del(.kubernetes.container_name)
      .kubernetes.namespace = del(.kubernetes.pod_namespace)
      .kubernetes.node = del(.kubernetes.pod_node_name)
      .kubernetes.pod = del(.kubernetes.pod_name)

      del(.source_type)
