transforms:
  tag_kubernetes_logs:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      .@source = "kubernetes"
      .@dataset = "kubernetes." + string!(.kubernetes.pod_namespace)
      .@namespace = "default"
