apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-ca
  namespace: vector
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDVjCCAj6gAwIBAgIRAJv2YfEbecZ+R02/LcA40KwwDQYJKoZIhvcNAQELBQAw
    NTEWMBQGA1UECxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJj
    aC1odHRwMB4XDTI2MDQxMTE1NDAzMFoXDTI3MDQxMTE1NTAzMFowNTEWMBQGA1UE
    CxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJjaC1odHRwMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzrgZWQF2TQbWmDX2rXU4JxVl
    2g373fOpTWUlfCy8vTMq0rq90qIcbTzwhkthrE5aG9JcoNPfVpTn01Eot72TZO9s
    HqMnV35nQbPyExe9S7Eh5TT7wIHBRRaLFSmbn6S1A4aT6OKNVYsDlI+FpPWfDdrG
    X8QaQydrW0HLG+5KYN4SaeVV58KgsuMIfZX/j2QAXV0ELK7WowbtFTrCpF5WMK9f
    VTQ/WwXFxNhsDJYF20mnuJKicJ3DFtYO8Iv5k/m+65AXdBCmtn/236LiJocPL80Z
    67QUt0gC0gNHXH0kFQPzBtQKCiguhlDuQLwizONoWxQVwruHjoR8A1Q4P54A8wID
    AQABo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBPC9Rzvvt5/V+DUqpAj
    GlLdxtJPMA0GCSqGSIb3DQEBCwUAA4IBAQBM+WoJhvDGV1zWvz3021fLFkD59W1k
    xiq33DC9UtgBtqwF6x2+vefZHzX+gFaZ9PCS7pgoIj57jkJBLrx8Djg9mcDLd+YX
    xoTNgKiptd8nyVzgAB66O9Dn+hL3VB6XrsT+KXvwsgSa/V2vHIVeKFfczHWFNsmN
    XbxsWcOpbVOPZL5G8/QHPJVLi1ncF+2/+aeudms1nxSvaePILy6Ypm1zWnEF1rIE
    X9IPvJx8I+YE2+8U+QqLblQT9oH8nmd1Yw5PAg8T/JTKoEE9AtR+yAwQ9bfLxC4B
    S9cVzHaicrveyxtEV1Eb2jtOAkh1alr7iS4NKhA4RupbHIbCnfQA+fYg
    -----END CERTIFICATE-----
