apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-secrets-reader
  namespace: vector
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vector-vault
  namespace: vector
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: https://vault.blackquartz.io
      path: secrets
      caProvider:
        type: ConfigMap
        name: black-quartz-root-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: vector
          serviceAccountRef:
            name: vector-secrets-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elastic-credentials
  namespace: vector
spec:
  secretStoreRef:
    name: vector-vault
    kind: SecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target: 
    name: vector-elastic-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: vector/elastic_user
        property: username
    - secretKey: password
      remoteRef:
        key: vector/elastic_user
        property: password
    