name: Test Vector Configuration

on:
  pull_request:
    paths:
      - config/**
      - tests/**

jobs:
  test-config:
    runs-on: ubuntu-latest
    container:
      image: timberio/vector:nightly-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Vector Configuration
        run: |
          vector validate \
            --config-dir config/agent/ \
            --no-environment

          vector validate \
            --config-dir config/aggregator/ \
            --no-environment

      - name: Test Vector Configuration
        run: |
          vector test \
            --config-dir config/agent \
            --config-dir tests/agent

          vector test \
            --config-dir config/aggregator \
            --config-dir tests/aggregator
